version: "3.8"
services:
  #=====================
  # https://traefik.docker.localhost
  # http://localhost:8080
  traefik:
    image: traefik:2.9.8
    container_name: traefik
    #restart: always
    depends_on:
      - openssl
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./docker/traefik/config.yml:/etc/traefik/config.yml:ro
      - ./docker/certs:/etc/certs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http,https"
      - "traefik.http.routers.traefik.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
  #=====================
  # https://portainer.docker.localhost
  # http://localhost:9000
  portainer:
    image: portainer/portainer-ce:2.17.1
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    #restart: always
    depends_on:
      - traefik
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - portainer:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http,https"
      - "traefik.http.routers.portainer.rule=Host(`portainer.docker.localhost`)"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
  #=====================
  # https://maildev.docker.localhost
  # http://localhost:1080
  maildev:
    image: maildev/maildev:2.0.5
    container_name: maildev
    #restart: always
    #command: bin/maildev --web 80 --smtp 25 --verbose STARTTLS
    healthcheck:
      disable: true
    depends_on:
      - traefik
    ports:
      - "1025:1025"
      - "1080:1080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.maildev.entrypoints=http,https"
      - "traefik.http.routers.maildev.rule=Host(`maildev.docker.localhost`)"
      - "traefik.http.routers.maildev.tls=true"
      - "traefik.http.services.maildev.loadbalancer.server.port=1080"
  #=====================
  openssl:
    image: ealis/openssl:1.0
    #restart: always
    container_name: openssl
    volumes:
      - ./docker/openssl:/openssl
      - ./docker/openssl/domains.ext:/domains.ext
      - ./docker/certs:/certs
volumes:
  portainer:
    name: portainer
networks:
  default:
    name: traefik